services:
  localstack:
    image: localstack/localstack:3.7.0
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      - localstack

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:8000
    depends_on:
      - backend
